-- Run this once if sms_db already exists (phpMyAdmin → SQL tab)
USE sms_db;

ALTER TABLE students
  ADD COLUMN IF NOT EXISTS gender VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS date_of_birth DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS section VARCHAR(10) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS guardian_name VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS guardian_phone VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT NULL;
